### ISSUE TITLE
Nix building stuck on `Building subPackage .`

### ISSUE THREAD

**Issue by auroraanna** [diamondburned/gotktrix#28]

**Comment by diamondburned** [comment]
Not stuck; cgo is just slow. Give it at least 15 minutes. Reopen the issue if it still doesn't build after 15 minutes, but check `ps` and see if `cc1` processes are still running first.

**Comment by diamondburned** [comment]
If it helps, use the patched Go in `overlay.nix`. The patches should make it build significantly faster.
