### ISSUE TITLE
Error while installing with go install

### ISSUE THREAD

**Issue by ghost** [diamondburned/gotktrix#32]
```
❯ go install -v github.com/diamondburned/gotktrix@latest
go: github.com/diamondburned/gotktrix@latest (in github.com/diamondburned/gotktrix@v0.1.3):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by diamondburned** [comment]
Oops.

**Comment by diamondburned** [comment]
The application kind of depends on https://github.com/chanbakjsd/gotrix/pull/23, but I think I'll just hard-fork the library.

**Comment by diamondburned** [comment]
See https://github.com/golang/go/issues/44840 for more information.

**Comment by nikolaosmoilanen** [comment]
Any updates on this issue, or known workarounds for the moment?

**Comment by diamondburned** [comment]
This should work now. I've [already hard-forked the library](https://github.com/diamondburned/gotktrix/blob/compound/go.mod#L12).

On an unrelated note, I might consider migrating to something like `mautrix/go` in the future.
