### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by PurpleBored** [diamondburned/gotktrix#45]
I mean the latest release on Github is from around 2 years ago and the latest commit is over one year old. Will there ever be a new update?

**Comment by diamondburned** [comment]
No :( 

Does this thing still work, even?

**Comment by PurpleBored** [comment]
aw very sad :( I still believe this client has the nicest UI of most Matrix clients. Also tbh never got it running in the first place so i have no idea if it still works lol

**Comment by diamondburned** [comment]
I'm closing this issue for now. I might work on another Matrix client in the future, but maintaining this one was already a lot of work for me, and Matrix's API is too clunky that I'm not sure if I'm ready to take up on that work.

Cinny is pretty decent in my experience. It's what I'm using right now, if that helps.
